# Generated by Django 3.1.4 on 2020-12-10 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Modification date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schema',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='csv_gen/static/users_files/', verbose_name='Schema file'),
        ),
    ]
