# Generated by Django 3.1.4 on 2020-12-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0002_auto_20201210_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
