# Generated by Django 3.1.4 on 2020-12-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_gen', '0003_schema_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='file',
        ),
        migrations.AddField(
            model_name='schema',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Schema file'),
        ),
    ]
